### ISSUE TITLE
Do not assume architecture based on the OS architecture

### ISSUE THREAD

**Issue by eXpl0it3r** [sandrohanea/PdfiumPrinter#21]
The native library loader currently assumes that if the OS architecture is x64, that the library to be loaded should also be x64, but it's still common to run x86 applications on x64 OS, and thus that path creation will be invalid and load a x64 library in a x86 will fail.

https://github.com/sandrohanea/PdfiumPrinter/blob/5fd27b02934b5c716c7a163ea60f660ac051887e/PdfiumPrinter/LibraryLoader/NativeLibraryLoader.cs#L44-L50

~~Additionally, the directory structure assumption no longer holds with the newer version of bblanchon.PDFiumV8.Win32 as the DLL is directly written to the output directory and no longer resides in a `x64` or `x86` directory.~~

Finally, what's the point of the library load functionality? Won't the actual import calls load the DLL itself via `DllImport`?

**Comment by eXpl0it3r** [comment]
Since the library loading isn't needed at all, one can also just override the loader with a stub:

```csharp
    public class Test
    {
        public void Printing()
        {
            NativeLibraryLoader.SetLibraryLoader(new CustomLibraryLoader());
            // ...
        }
    }

    internal class CustomLibraryLoader : ILibraryLoader
    {
        public LoadResult OpenLibrary(string fileName)
        {
            return LoadResult.Success;
        }
    }
```

**Comment by sandrohanea** [comment]
It is quite common to assume the architecture based on the OS architecture (I'm doing the same for whisper.net and observed it in multiple dotnet wrappers for native libraries).

The scope of the LibraryLoader is to ensure that the library is loaded for different possible paths (`e.g. {platform}-{architecture}`) but also to ensure that a clear exception will be thrown if the native Pdfium printer won't be found:
https://github.com/sandrohanea/PdfiumPrinter/blob/5fd27b02934b5c716c7a163ea60f660ac051887e/PdfiumPrinter/LibraryLoader/NativeLibraryLoader.cs#L88

Otherwise, a generic DllNotFoundException will be thrown. 

Indeed, if someone wants to create a custom library loader, they can use something similar with the one that you show in the example.

For skipping the load, you don't need to create a custom loader, but you can simply use [PdfLibrary](https://github.com/sandrohanea/PdfiumPrinter/blob/4d9d34b3f592a5a0cdd371fedf1f853158939486/PdfiumPrinter/PdfLibrary.cs#L26):

```
PdfLibrary.EnsureLoaded(bypassLoading: true);
```

There you can also use a custom path for loading the library.

**Comment by eXpl0it3r** [comment]
> It is quite common to assume the architecture based on the OS architecture (I'm doing the same for whisper.net and observed it in multiple dotnet wrappers for native libraries).

Maybe it's common, but it's still wrong. The code breaks if you build/run for x86 on a x64 system.

> The scope of the LibraryLoader is to ensure that the library is loaded for different possible paths (`e.g. {platform}-{architecture}`) but also to ensure that a clear exception will be thrown if the native Pdfium printer won't be found:

Loading the DLL twice just to get a better error if it fails, is rather wasteful.  
Wouldn't it make more sense to handle the exception and try to get more information at that point?

Don't think DllImport will just use, what's already been loaded into memory, or does it?

> `PdfLibrary.EnsureLoaded(bypassLoading: true);`

That's good to know, thanks!

**Comment by eXpl0it3r** [comment]
> `PdfLibrary.EnsureLoaded(bypassLoading: true);`

That's good to know, thanks!

**Comment by sandrohanea** [comment]
The library will not be loaded twice, but the DllImport will re-use the existing handle that was loaded with LoadLibrary() or dlopen (based on the OS) when it will resolve the handle.

It's not specific to DllImport but to LoadLibrary and dlopen (which are used by DllImport to load the library):
![image](https://github.com/user-attachments/assets/935d3230-ae57-4cf3-8813-ef36ab876988)

https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya

https://www.man7.org/linux/man-pages/man3/dlopen.3.html#:~:text=dlopen%28%29%20The%20function%20dlopen%20%28%29%20loads%20the%20dynamic,returns%20an%20opaque%20%22handle%22%20for%20the%20loaded%20object.

![image](https://github.com/user-attachments/assets/add945a3-a2c6-4c00-b2c0-d86374f49a56)

**Comment by eXpl0it3r** [comment]
Interesting, that I didn't know. Thank you for pointing to the source! 🙂 

Now, if there was just a way to load the 32-bit library on a 64-bit OS.  
Unfortunately we can't "just" switch to 64-bit at this point.

**Comment by sandrohanea** [comment]
You should be able to use:

`PdfLibrary.EnsureLoaded("thePathTox86Library.dll") instead of `bypassLoading: true`

For example, if you're using [bblanchon](https://www.nuget.org/packages/bblanchon.PDFium.Win32/) build for Win32, you can use:

`PdfLibrary.EnsureLoaded("runtime/win-x86/pdfium.dll")`

Make sure you call this before loading any PDF file.

**Comment by eXpl0it3r** [comment]
I can indeed override it or just let DllImport correctly handle the architecture with the bypass.

However, it would be even better if PdfiumPrinter could make this distinction on its own.

Unfortunately, I haven't found an easy way to determine the actual "runtime architecture".
